name: Check for passwords

on:
  repository_dispatch:
    types: [org-workflow-bot]
  workflow_dispatch:
  schedule:
    - cron: '03 14 * * *'

jobs:
  register:
    runs-on: ubuntu-latest
    steps:

      - uses: SvanBoxel/organization-workflow@main
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}

      - name: Check password
        uses: AlicanAkkus/pinder-action@0.1
