name: I know what you did last summer

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['']    
    
    steps:

      - uses: SvanBoxel/organization-workflow@main
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }}

      - name: Checkout
        uses: actions/checkout@v3
#         with:
#           repository: ${{ github.event.client_payload.repository.full_name }}
#           ref: ${{ github.event.client_payload.sha }}
#           token: ${{ github.event.client_payload.token }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
#         with:
#           languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

