name: Enforce advanced security scanning

on:
  push:
    branches: [ main, master ]
    
  workflow_dispatch:
  schedule:
    - cron: '25 13 * * *'

jobs:
  build:
    name: Enforce advanced security scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run enforcer tool
      uses: docker://ghcr.io/zkoppert/advanced-security-enforcer:v2
      env:
        GH_ACTOR: ${{ secrets.GH_ACTOR }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        PR_BODY: your text goes here
        HOURS_DELAY: 120
